import express, { type Request, Response, NextFunction } from "express";
import { createServer } from "http";
import path from "path";
import fs from "fs";
import session from "express-session";
import passport from "passport";
import ConnectPgSimple from "connect-pg-simple";
import { registerRoutes } from "./routes";
import { setupVite, serveStatic, log } from "./vite";

const app = express();
const isProduction = process.env.NODE_ENV === 'production';
const port = parseInt(process.env.PORT || '5000', 10);

// Serve uploaded media files (images/videos generated by AI) — must be early in chain
const uploadsBasePath = path.join(process.cwd(), "uploads");
if (!fs.existsSync(uploadsBasePath)) {
  fs.mkdirSync(uploadsBasePath, { recursive: true });
}
app.use("/uploads", express.static(uploadsBasePath, { maxAge: "1h" }));

if (isProduction) {
  const distPath = path.resolve(process.cwd(), "dist", "public");
  if (fs.existsSync(distPath)) {
    // Hashed assets (JS/CSS/images) — immutable, cache for 1 year
    app.use(
      "/assets",
      express.static(path.join(distPath, "assets"), {
        maxAge: "1y",
        immutable: true,
      }),
    );
    // Root files (index.html, favicon) — short cache, revalidate on deploy
    app.use(
      express.static(distPath, {
        maxAge: "1h",
        setHeaders(res, filePath) {
          if (filePath.endsWith(".html")) {
            res.setHeader("Cache-Control", "no-cache");
          }
        },
      }),
    );
  }
}

// Stripe webhook placeholder (Stripe integration currently paused)
app.post('/api/stripe/webhook', express.raw({ type: 'application/json' }), (_req, res) => {
  res.status(200).json({ received: true });
});

app.use(express.json());
app.use(express.urlencoded({ extended: false }));

if (!process.env.SESSION_SECRET) {
  console.error('FATAL: SESSION_SECRET environment variable is required');
  process.exit(1);
}

function buildSessionStore() {
  try {
    const PgSession = ConnectPgSimple(session);
    return new PgSession({
      conString: process.env.DATABASE_URL,
      createTableIfMissing: true,
    });
  } catch (err) {
    console.warn('PgSession store failed to initialize, falling back to MemoryStore:', err);
    return undefined;
  }
}

const sessionStore = buildSessionStore();

const sessionMiddleware = session({
  ...(sessionStore ? { store: sessionStore } : {}),
  secret: process.env.SESSION_SECRET,
  resave: false,
  saveUninitialized: false,
  cookie: {
    secure: isProduction,
    httpOnly: true,
    sameSite: 'lax',
    maxAge: 24 * 60 * 60 * 1000
  },
  proxy: isProduction
});

const passportInit = passport.initialize();
const passportSession = passport.session();

app.use((req, res, next) => {
  if (req.path.startsWith("/api")) {
    sessionMiddleware(req, res, (err?: any) => {
      if (err) return next(err);
      passportInit(req, res, (err2?: any) => {
        if (err2) return next(err2);
        passportSession(req, res, next);
      });
    });
  } else {
    next();
  }
});

app.use((req, res, next) => {
  const start = Date.now();
  const reqPath = req.path;
  let capturedJsonResponse: Record<string, any> | undefined = undefined;

  const originalResJson = res.json;
  res.json = function (bodyJson, ...args) {
    capturedJsonResponse = bodyJson;
    return originalResJson.apply(res, [bodyJson, ...args]);
  };

  res.on("finish", () => {
    const duration = Date.now() - start;
    if (reqPath.startsWith("/api")) {
      let logLine = `${req.method} ${reqPath} ${res.statusCode} in ${duration}ms`;
      if (capturedJsonResponse) {
        logLine += ` :: ${JSON.stringify(capturedJsonResponse)}`;
      }
      if (logLine.length > 80) {
        logLine = logLine.slice(0, 79) + "…";
      }
      log(logLine);
    }
  });

  next();
});

const httpServer = createServer(app);

httpServer.listen({ port, host: "0.0.0.0", reusePort: true }, () => {
  log(`serving on port ${port}`);
});

(async () => {
  if (process.env.INFERENCE_API_KEY) {
    try {
      const { execSync } = await import("child_process");
      const home = process.env.HOME || "/home/runner";
      const infshBin = path.join(home, ".local", "bin", "infsh");
      if (!fs.existsSync(infshBin)) {
        console.log("[STARTUP] Installing inference.sh CLI...");
        const binDir = path.join(home, ".local", "bin");
        if (!fs.existsSync(binDir)) fs.mkdirSync(binDir, { recursive: true });
        execSync("curl -fsSL https://inference.sh/install.sh | sh", {
          env: { ...process.env, HOME: home },
          timeout: 30000,
          stdio: "pipe",
        });
      }
      if (fs.existsSync(infshBin)) {
        console.log(`[STARTUP] inference.sh CLI ready at ${infshBin}`);
      }
    } catch (e: any) {
      console.warn(`[STARTUP] inference.sh CLI install failed (non-blocking): ${e.message}`);
    }
  }

  await registerRoutes(app, httpServer);

  app.use((err: any, _req: Request, res: Response, _next: NextFunction) => {
    const status = err.status || err.statusCode || 500;
    const message = err.message || "Internal Server Error";
    console.error(`[Error] ${status}: ${message}`);
    if (!res.headersSent) {
      res.status(status).json({ message });
    }
  });

  if (app.get("env") === "development") {
    await setupVite(app, httpServer);
  } else {
    serveStatic(app);
  }
})();
