import { useState, useMemo } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Link } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import {
  AlertTriangle,
  ArrowLeft,
  ArrowUpRight,
  BarChart3,
  Bot,
  Building2,
  Calendar,
  CheckCircle2,
  Clock,
  DollarSign,
  Eye,
  Lightbulb,
  Loader2,
  Mail,
  Merge,
  Phone,
  RefreshCw,
  Rocket,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  User,
  Zap,
} from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import type { AutomationDiscoveryRequest } from "@shared/schema";
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";

type OutlineData = {
  summary: string;
  recommendedApproach: string;
  proposedSolution: string[];
  estimatedTimeline: string;
  estimatedBudget: string;
  keyBenefits: string[];
  potentialChallenges?: string[];
  nextSteps: string[];
  additionalRecommendations?: string;
  generatedAt?: string;
  modelUsed?: string;
};

function OutlineDisplay({ outline, providerName }: { outline: OutlineData; providerName: string }) {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Bot className="w-4 h-4" />
        Generated by {outline.modelUsed || providerName}
        {outline.generatedAt && (
          <span>on {new Date(outline.generatedAt).toLocaleDateString()}</span>
        )}
      </div>

      {/* Executive Summary - Visual Header */}
      <div className="relative overflow-hidden rounded-xl bg-gradient-to-br from-primary/10 via-primary/5 to-background p-5 border border-primary/20">
        <div className="absolute top-0 right-0 w-24 h-24 bg-primary/10 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2" />
        <div className="relative">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-primary/20 rounded-lg">
              <BarChart3 className="w-4 h-4 text-primary" />
            </div>
            <h3 className="font-semibold text-lg">Executive Summary</h3>
          </div>
          <p className="text-muted-foreground leading-relaxed">{outline.summary}</p>
        </div>
      </div>

      {/* Recommended Approach */}
      <div className="p-5 bg-muted/50 rounded-xl border border-border/50">
        <div className="flex items-center gap-3 mb-3">
          <div className="p-2 bg-blue-500/10 rounded-lg">
            <Bot className="w-4 h-4 text-blue-500" />
          </div>
          <h3 className="font-semibold text-lg">Recommended Approach</h3>
        </div>
        <p className="text-muted-foreground leading-relaxed">{outline.recommendedApproach}</p>
      </div>

      {/* Implementation Roadmap - Visual Steps */}
      <div className="p-5 bg-muted/50 rounded-xl border border-border/50">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 bg-purple-500/10 rounded-lg">
            <Rocket className="w-4 h-4 text-purple-500" />
          </div>
          <h3 className="font-semibold text-lg">Implementation Roadmap</h3>
        </div>
        <div className="space-y-3">
          {outline.proposedSolution?.map((step, i) => (
            <div key={i} className="relative flex gap-4">
              {i < (outline.proposedSolution?.length || 0) - 1 && (
                <div className="absolute left-[14px] top-8 w-0.5 h-full bg-gradient-to-b from-primary/40 to-primary/10" />
              )}
              <div className="flex-shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-primary to-primary/70 text-primary-foreground text-xs font-medium flex items-center justify-center shadow-sm">
                {i + 1}
              </div>
              <div className="flex-1 pb-3">
                <p className="text-muted-foreground pt-1 text-sm">{step}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Timeline & Budget Grid */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="p-5 bg-gradient-to-r from-amber-500/10 to-orange-500/10 rounded-xl border border-amber-500/20">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-amber-500/20 rounded-lg">
              <Calendar className="w-4 h-4 text-amber-600" />
            </div>
            <h3 className="font-semibold">Estimated Timeline</h3>
          </div>
          <p className="text-muted-foreground font-medium">{outline.estimatedTimeline}</p>
        </div>
        <div className="p-5 bg-gradient-to-r from-emerald-500/10 to-green-500/10 rounded-xl border border-emerald-500/20">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-emerald-500/20 rounded-lg">
              <DollarSign className="w-4 h-4 text-emerald-600" />
            </div>
            <h3 className="font-semibold">Estimated Budget</h3>
          </div>
          <p className="text-muted-foreground font-medium">{outline.estimatedBudget}</p>
        </div>
      </div>

      {/* Key Benefits - Visual Grid */}
      <div className="p-5 bg-muted/50 rounded-xl border border-border/50">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 bg-green-500/10 rounded-lg">
            <TrendingUp className="w-4 h-4 text-green-500" />
          </div>
          <h3 className="font-semibold text-lg">Key Benefits</h3>
        </div>
        <div className="grid md:grid-cols-2 gap-2">
          {outline.keyBenefits?.map((benefit, i) => (
            <div key={i} className="flex items-start gap-2 p-2 bg-green-500/5 rounded-lg border border-green-500/10">
              <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />
              <span className="text-muted-foreground text-sm">{benefit}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Potential Challenges */}
      {outline.potentialChallenges && outline.potentialChallenges.length > 0 && (
        <div className="p-5 bg-yellow-500/5 border border-yellow-500/20 rounded-xl">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-yellow-500/20 rounded-lg">
              <AlertTriangle className="w-4 h-4 text-yellow-600" />
            </div>
            <h3 className="font-semibold">Potential Challenges</h3>
          </div>
          <ul className="space-y-2">
            {outline.potentialChallenges.map((challenge, i) => (
              <li key={i} className="text-sm text-muted-foreground flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-yellow-500" />
                {challenge}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Next Steps */}
      <div className="p-5 bg-gradient-to-r from-blue-500/10 to-indigo-500/10 rounded-xl border border-blue-500/20">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 bg-blue-500/20 rounded-lg">
            <ArrowUpRight className="w-4 h-4 text-blue-500" />
          </div>
          <h3 className="font-semibold text-lg">Next Steps</h3>
        </div>
        <div className="space-y-2">
          {outline.nextSteps?.map((step, i) => (
            <div key={i} className="flex gap-3 items-start p-2 bg-background/50 rounded-lg">
              <div className="flex-shrink-0 w-5 h-5 rounded-full bg-blue-500/20 text-blue-600 text-xs font-medium flex items-center justify-center">
                {i + 1}
              </div>
              <span className="text-muted-foreground text-sm">{step}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Additional Recommendations */}
      {outline.additionalRecommendations && (
        <div className="p-5 bg-muted/50 rounded-xl border border-border/50">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 bg-indigo-500/10 rounded-lg">
              <Lightbulb className="w-4 h-4 text-indigo-500" />
            </div>
            <h3 className="font-semibold">Additional Recommendations</h3>
          </div>
          <p className="text-muted-foreground leading-relaxed">{outline.additionalRecommendations}</p>
        </div>
      )}
    </div>
  );
}

function NoOutlineMessage({ provider }: { provider: string }) {
  return (
    <div className="text-center py-8">
      <Bot className="w-10 h-10 mx-auto text-muted-foreground mb-3" />
      <h3 className="font-semibold mb-1">{provider} Outline Not Available</h3>
      <p className="text-sm text-muted-foreground">
        This outline hasn't been generated yet or the provider was unavailable.
      </p>
    </div>
  );
}

// Analysis functions for comparing outlines
function analyzeOutlineAgreement(openai: OutlineData | null, gemini: OutlineData | null): {
  confidenceScore: number;
  agreements: string[];
  discrepancies: { field: string; openai: string; gemini: string; severity: 'low' | 'medium' | 'high' }[];
} {
  if (!openai || !gemini) {
    return { confidenceScore: 0, agreements: [], discrepancies: [] };
  }

  const agreements: string[] = [];
  const discrepancies: { field: string; openai: string; gemini: string; severity: 'low' | 'medium' | 'high' }[] = [];

  // Helper to safely get truncated text
  const truncate = (text: string | undefined | null, maxLen: number = 100): string => {
    if (!text || text.trim() === '') return 'N/A';
    return text.length > maxLen ? text.substring(0, maxLen) + '...' : text;
  };

  // Compare recommended approach
  const openaiApproach = openai.recommendedApproach?.toLowerCase() || '';
  const geminiApproach = gemini.recommendedApproach?.toLowerCase() || '';
  
  if (openaiApproach && geminiApproach) {
    if (openaiApproach.includes('hybrid') && geminiApproach.includes('hybrid')) {
      agreements.push('Both recommend a hybrid approach');
    } else if (openaiApproach.includes('ai agent') && geminiApproach.includes('ai agent')) {
      agreements.push('Both recommend AI agent approach');
    } else if (openaiApproach.includes('software') && geminiApproach.includes('software')) {
      agreements.push('Both recommend software automation');
    } else if (openaiApproach.includes('automation') && geminiApproach.includes('automation')) {
      agreements.push('Both recommend automation solutions');
    } else {
      discrepancies.push({
        field: 'Recommended Approach',
        openai: truncate(openai.recommendedApproach),
        gemini: truncate(gemini.recommendedApproach),
        severity: 'medium'
      });
    }
  }

  // Compare timeline estimates
  const openaiTimeline = openai.estimatedTimeline?.toLowerCase() || '';
  const geminiTimeline = gemini.estimatedTimeline?.toLowerCase() || '';
  const extractWeeks = (str: string): number => {
    const match = str.match(/(\d+)/);
    return match ? parseInt(match[1]) : 0;
  };
  const openaiWeeks = extractWeeks(openaiTimeline);
  const geminiWeeks = extractWeeks(geminiTimeline);
  if (openaiWeeks > 0 && geminiWeeks > 0) {
    const diff = Math.abs(openaiWeeks - geminiWeeks);
    if (diff <= 2) {
      agreements.push(`Similar timeline estimates (~${Math.round((openaiWeeks + geminiWeeks) / 2)} weeks)`);
    } else {
      discrepancies.push({
        field: 'Timeline',
        openai: openai.estimatedTimeline || 'N/A',
        gemini: gemini.estimatedTimeline || 'N/A',
        severity: diff > 4 ? 'high' : 'medium'
      });
    }
  }

  // Compare number of solution steps
  const openaiSteps = openai.proposedSolution?.length || 0;
  const geminiSteps = gemini.proposedSolution?.length || 0;
  if (openaiSteps > 0 && geminiSteps > 0) {
    if (Math.abs(openaiSteps - geminiSteps) <= 2) {
      agreements.push(`Similar solution complexity (${Math.round((openaiSteps + geminiSteps) / 2)} steps)`);
    } else {
      discrepancies.push({
        field: 'Solution Complexity',
        openai: `${openaiSteps} steps`,
        gemini: `${geminiSteps} steps`,
        severity: 'low'
      });
    }
  }

  // Compare number of benefits identified
  const openaiB = openai.keyBenefits?.length || 0;
  const geminiB = gemini.keyBenefits?.length || 0;
  if (openaiB > 0 && geminiB > 0 && Math.abs(openaiB - geminiB) <= 2) {
    agreements.push('Similar benefit assessment');
  }

  // Calculate confidence score (0-100) with proper weighting
  const totalChecks = 4;
  const agreementCount = agreements.length;
  const highSeverityCount = discrepancies.filter(d => d.severity === 'high').length;
  const mediumSeverityCount = discrepancies.filter(d => d.severity === 'medium').length;
  
  // Penalize both high and medium severity discrepancies
  const confidenceScore = Math.round(
    ((agreementCount / totalChecks) * 100) - (highSeverityCount * 25) - (mediumSeverityCount * 10)
  );

  return {
    confidenceScore: Math.max(0, Math.min(100, confidenceScore)),
    agreements,
    discrepancies
  };
}

function ConfidenceIndicator({ score }: { score: number }) {
  const getColor = () => {
    if (score >= 70) return 'bg-green-500';
    if (score >= 40) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const getLabel = () => {
    if (score >= 70) return 'High Agreement';
    if (score >= 40) return 'Moderate Agreement';
    return 'Low Agreement';
  };

  return (
    <div className="flex items-center gap-3 p-3 rounded-lg bg-muted">
      <ShieldCheck className="w-5 h-5 text-primary" />
      <div className="flex-1">
        <div className="flex items-center justify-between mb-1">
          <span className="text-sm font-medium">AI Confidence Score</span>
          <span className="text-sm font-bold">{score}%</span>
        </div>
        <div className="h-2 bg-background rounded-full overflow-hidden">
          <div 
            className={`h-full ${getColor()} transition-all duration-500`}
            style={{ width: `${score}%` }}
          />
        </div>
        <p className="text-xs text-muted-foreground mt-1">{getLabel()} between DeepSeek V4 Pro and MiniMax M2.7</p>
      </div>
    </div>
  );
}

function DiscrepancyAlerts({ discrepancies }: { 
  discrepancies: { field: string; openai: string; gemini: string; severity: 'low' | 'medium' | 'high' }[] 
}) {
  const highSeverity = discrepancies.filter(d => d.severity === 'high');
  const mediumSeverity = discrepancies.filter(d => d.severity === 'medium');

  if (highSeverity.length === 0 && mediumSeverity.length === 0) {
    return null;
  }

  return (
    <div className="space-y-2">
      {highSeverity.map((d, i) => (
        <Alert key={`high-${i}`} variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Significant Discrepancy: {d.field}</AlertTitle>
          <AlertDescription className="mt-2 space-y-1 text-sm">
            <p><strong>OpenAI:</strong> {d.openai}</p>
            <p><strong>Gemini:</strong> {d.gemini}</p>
          </AlertDescription>
        </Alert>
      ))}
      {mediumSeverity.map((d, i) => (
        <Alert key={`med-${i}`} className="border-yellow-500/50 bg-yellow-500/10">
          <AlertTriangle className="h-4 w-4 text-yellow-600" />
          <AlertTitle className="text-yellow-600">Difference Detected: {d.field}</AlertTitle>
          <AlertDescription className="mt-2 space-y-1 text-sm">
            <p><strong>OpenAI:</strong> {d.openai}</p>
            <p><strong>Gemini:</strong> {d.gemini}</p>
          </AlertDescription>
        </Alert>
      ))}
    </div>
  );
}

function AgreementsList({ agreements }: { agreements: string[] }) {
  if (agreements.length === 0) return null;
  
  return (
    <div className="p-3 rounded-lg bg-green-500/10 border border-green-500/20">
      <h4 className="font-medium text-green-700 dark:text-green-400 mb-2 flex items-center gap-2">
        <CheckCircle2 className="w-4 h-4" /> Points of Agreement
      </h4>
      <ul className="space-y-1">
        {agreements.map((a, i) => (
          <li key={i} className="text-sm text-muted-foreground flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500" />
            {a}
          </li>
        ))}
      </ul>
    </div>
  );
}

const STATUS_COLORS: Record<string, string> = {
  new: '#3b82f6',
  processing: '#eab308',
  outline_generated: '#22c55e',
  reviewed: '#a855f7',
  converted: '#6366f1',
};

const STATUS_LABELS: Record<string, string> = {
  new: 'New',
  processing: 'Processing',
  outline_generated: 'Outline Ready',
  reviewed: 'Reviewed',
  converted: 'Converted',
};

function DiscoveryDashboard({ requests }: { requests: AutomationDiscoveryRequest[] }) {
  const statusData = useMemo(() => {
    const counts: Record<string, number> = {};
    requests.forEach(r => {
      counts[r.status] = (counts[r.status] || 0) + 1;
    });
    return Object.entries(counts).map(([status, count]) => ({
      name: STATUS_LABELS[status] || status,
      value: count,
      color: STATUS_COLORS[status] || '#94a3b8',
    }));
  }, [requests]);

  const timelineData = useMemo(() => {
    const last7Days: Record<string, number> = {};
    const now = new Date();
    for (let i = 6; i >= 0; i--) {
      const date = new Date(now);
      date.setDate(date.getDate() - i);
      const key = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
      last7Days[key] = 0;
    }
    requests.forEach(r => {
      if (r.createdAt) {
        const date = new Date(r.createdAt);
        const key = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
        if (key in last7Days) {
          last7Days[key]++;
        }
      }
    });
    return Object.entries(last7Days).map(([date, count]) => ({ date, requests: count }));
  }, [requests]);

  const stats = useMemo(() => {
    const total = requests.length;
    const newCount = requests.filter(r => r.status === 'new').length;
    const readyCount = requests.filter(r => r.status === 'outline_generated').length;
    const convertedCount = requests.filter(r => r.status === 'converted').length;
    return { total, newCount, readyCount, convertedCount };
  }, [requests]);

  return (
    <div className="mb-6 space-y-4">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-blue-500/10">
                <BarChart3 className="w-5 h-5 text-blue-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.total}</p>
                <p className="text-xs text-muted-foreground">Total Requests</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-yellow-500/10">
                <Clock className="w-5 h-5 text-yellow-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.newCount}</p>
                <p className="text-xs text-muted-foreground">Pending Review</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-green-500/10">
                <CheckCircle2 className="w-5 h-5 text-green-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.readyCount}</p>
                <p className="text-xs text-muted-foreground">Outlines Ready</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-500/10">
                <TrendingUp className="w-5 h-5 text-purple-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.convertedCount}</p>
                <p className="text-xs text-muted-foreground">Converted</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Status Distribution</CardTitle>
          </CardHeader>
          <CardContent>
            {statusData.length > 0 ? (
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie
                    data={statusData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={2}
                    dataKey="value"
                    label={({ name, value }) => `${name}: ${value}`}
                    labelLine={false}
                  >
                    {statusData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-[200px] flex items-center justify-center text-muted-foreground">
                No data yet
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Requests (Last 7 Days)</CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={timelineData}>
                <XAxis dataKey="date" tick={{ fontSize: 10 }} />
                <YAxis allowDecimals={false} tick={{ fontSize: 10 }} />
                <Tooltip />
                <Bar dataKey="requests" fill="#6366f1" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

export default function AutomationDiscoveryAdmin() {
  const [selectedRequest, setSelectedRequest] = useState<string | null>(null);
  const { toast } = useToast();

  const { data: requests, isLoading } = useQuery<AutomationDiscoveryRequest[]>({
    queryKey: ['/api/admin/automation-discoveries'],
  });

  const regenerateMutation = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiRequest("POST", `/api/admin/automation-discoveries/${id}/regenerate-outline`);
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: "Regeneration Started",
        description: "AI is regenerating both outlines.",
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/automation-discoveries'] });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to regenerate outline",
        variant: "destructive",
      });
    },
  });

  const mergeMutation = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiRequest("POST", `/api/admin/automation-discoveries/${id}/merge`);
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: "Merged Outline Created",
        description: "Best elements from both AI models have been combined.",
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/automation-discoveries'] });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to merge outlines",
        variant: "destructive",
      });
    },
  });

  const selectedData = requests?.find(r => r.id === selectedRequest);
  
  // Analyze outlines for confidence and discrepancies
  const analysis = selectedData ? analyzeOutlineAgreement(
    selectedData.aiOutline as OutlineData | null,
    (selectedData as any).geminiOutline as OutlineData | null
  ) : null;

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'new':
        return <Badge className="bg-blue-500/20 text-blue-600 dark:text-blue-400">New</Badge>;
      case 'processing':
        return <Badge className="bg-yellow-500/20 text-yellow-600 dark:text-yellow-400">Processing</Badge>;
      case 'outline_generated':
        return <Badge className="bg-green-500/20 text-green-600 dark:text-green-400">Outline Ready</Badge>;
      case 'reviewed':
        return <Badge className="bg-purple-500/20 text-purple-600 dark:text-purple-400">Reviewed</Badge>;
      case 'converted':
        return <Badge className="bg-primary/20 text-primary">Converted</Badge>;
      default:
        return <Badge variant="secondary">{status}</Badge>;
    }
  };

  const getPriorityBadge = (priority: string | null) => {
    switch (priority) {
      case 'urgent':
        return <Badge className="bg-red-500/20 text-red-600 dark:text-red-400">Urgent</Badge>;
      case 'high':
        return <Badge className="bg-orange-500/20 text-orange-600 dark:text-orange-400">High</Badge>;
      case 'medium':
        return <Badge className="bg-yellow-500/20 text-yellow-600 dark:text-yellow-400">Medium</Badge>;
      case 'low':
        return <Badge className="bg-gray-500/20 text-gray-600 dark:text-gray-400">Low</Badge>;
      default:
        return null;
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <Link href="/admin">
              <Button variant="ghost" size="icon" data-testid="button-back">
                <ArrowLeft className="w-4 h-4" />
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold">Automation Discovery Requests</h1>
              <p className="text-muted-foreground">Review and manage incoming automation requests</p>
            </div>
          </div>
        </div>

        {requests && requests.length > 0 && (
          <DiscoveryDashboard requests={requests} />
        )}

        <div className="grid lg:grid-cols-3 gap-6">
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Requests</CardTitle>
                <CardDescription>Click to view details</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[calc(100vh-280px)]">
                  {requests?.length === 0 ? (
                    <div className="p-6 text-center text-muted-foreground">
                      No discovery requests yet
                    </div>
                  ) : (
                    <div className="divide-y">
                      {requests?.map((request) => (
                        <button
                          key={request.id}
                          onClick={() => setSelectedRequest(request.id)}
                          className={`w-full p-4 text-left hover-elevate transition-colors ${
                            selectedRequest === request.id ? 'bg-muted' : ''
                          }`}
                          data-testid={`request-item-${request.id}`}
                        >
                          <div className="flex items-start justify-between gap-2 mb-2">
                            <span className="font-medium truncate">{request.processName}</span>
                            {getStatusBadge(request.status)}
                          </div>
                          <div className="text-sm text-muted-foreground mb-1">
                            {request.companyName}
                          </div>
                          <div className="flex items-center gap-2 text-xs text-muted-foreground">
                            <User className="w-3 h-3" />
                            {request.contactName}
                            {request.priorityLevel && (
                              <>
                                <span className="mx-1">|</span>
                                {getPriorityBadge(request.priorityLevel)}
                              </>
                            )}
                          </div>
                        </button>
                      ))}
                    </div>
                  )}
                </ScrollArea>
              </CardContent>
            </Card>
          </div>

          <div className="lg:col-span-2">
            {selectedData ? (
              <Card>
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div>
                      <CardTitle className="text-xl">{selectedData.processName}</CardTitle>
                      <CardDescription className="flex items-center gap-2 mt-1">
                        <Building2 className="w-4 h-4" />
                        {selectedData.companyName}
                        {selectedData.industry && ` | ${selectedData.industry}`}
                      </CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      {getStatusBadge(selectedData.status)}
                      {getPriorityBadge(selectedData.priorityLevel)}
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="details">
                    <TabsList className="mb-4">
                      <TabsTrigger value="details">Request Details</TabsTrigger>
                      <TabsTrigger value="outline" className="flex items-center gap-1">
                        <Sparkles className="w-3 h-3" />
                        AI Outline
                      </TabsTrigger>
                    </TabsList>

                    <TabsContent value="details">
                      <ScrollArea className="h-[calc(100vh-400px)]">
                        <div className="space-y-6 pr-4">
                          <div className="grid md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                              <h4 className="font-medium flex items-center gap-2">
                                <User className="w-4 h-4" /> Contact Information
                              </h4>
                              <div className="text-sm space-y-1 text-muted-foreground">
                                <p>{selectedData.contactName}</p>
                                {selectedData.jobTitle && <p>{selectedData.jobTitle}</p>}
                                <p className="flex items-center gap-1">
                                  <Mail className="w-3 h-3" /> {selectedData.contactEmail}
                                </p>
                                {selectedData.contactPhone && (
                                  <p className="flex items-center gap-1">
                                    <Phone className="w-3 h-3" /> {selectedData.contactPhone}
                                  </p>
                                )}
                              </div>
                            </div>
                            <div className="space-y-2">
                              <h4 className="font-medium flex items-center gap-2">
                                <Building2 className="w-4 h-4" /> Company Details
                              </h4>
                              <div className="text-sm space-y-1 text-muted-foreground">
                                <p>{selectedData.companyName}</p>
                                {selectedData.industry && <p>Industry: {selectedData.industry}</p>}
                                {selectedData.companySize && <p>Size: {selectedData.companySize} employees</p>}
                              </div>
                            </div>
                          </div>

                          <Separator />

                          <div className="space-y-4">
                            <h4 className="font-medium">Process Description</h4>
                            <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                              {selectedData.processDescription}
                            </p>
                            <div className="grid md:grid-cols-3 gap-4 text-sm">
                              {selectedData.currentTools && (
                                <div>
                                  <span className="font-medium">Current Tools:</span>
                                  <p className="text-muted-foreground">{selectedData.currentTools}</p>
                                </div>
                              )}
                              {selectedData.processFrequency && (
                                <div>
                                  <span className="font-medium">Frequency:</span>
                                  <p className="text-muted-foreground">{selectedData.processFrequency}</p>
                                </div>
                              )}
                              {selectedData.timeSpentPerWeek && (
                                <div>
                                  <span className="font-medium">Time/Week:</span>
                                  <p className="text-muted-foreground">{selectedData.timeSpentPerWeek}</p>
                                </div>
                              )}
                            </div>
                          </div>

                          <Separator />

                          <div className="space-y-4">
                            <h4 className="font-medium flex items-center gap-2">
                              <Target className="w-4 h-4" /> Pain Points
                            </h4>
                            <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                              {selectedData.painPoints}
                            </p>
                          </div>

                          <div className="space-y-4">
                            <h4 className="font-medium flex items-center gap-2">
                              <Zap className="w-4 h-4" /> Desired Outcome
                            </h4>
                            <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                              {selectedData.desiredOutcome}
                            </p>
                          </div>

                          {(selectedData.dataSourcesUsed || selectedData.integrationNeeds) && (
                            <>
                              <Separator />
                              <div className="grid md:grid-cols-2 gap-4">
                                {selectedData.dataSourcesUsed && (
                                  <div className="space-y-2">
                                    <h4 className="font-medium">Data Sources</h4>
                                    <p className="text-sm text-muted-foreground">{selectedData.dataSourcesUsed}</p>
                                  </div>
                                )}
                                {selectedData.integrationNeeds && (
                                  <div className="space-y-2">
                                    <h4 className="font-medium">Integration Needs</h4>
                                    <p className="text-sm text-muted-foreground">{selectedData.integrationNeeds}</p>
                                  </div>
                                )}
                              </div>
                            </>
                          )}

                          <Separator />

                          <div className="grid md:grid-cols-3 gap-4 text-sm">
                            {selectedData.timeline && (
                              <div>
                                <span className="font-medium flex items-center gap-1">
                                  <Calendar className="w-3 h-3" /> Timeline
                                </span>
                                <p className="text-muted-foreground">{selectedData.timeline}</p>
                              </div>
                            )}
                            {selectedData.budgetRange && (
                              <div>
                                <span className="font-medium">Budget Range</span>
                                <p className="text-muted-foreground">{selectedData.budgetRange}</p>
                              </div>
                            )}
                            {selectedData.preferredApproach && (
                              <div>
                                <span className="font-medium">Preferred Approach</span>
                                <p className="text-muted-foreground capitalize">
                                  {selectedData.preferredApproach.replace(/_/g, ' ')}
                                </p>
                              </div>
                            )}
                          </div>

                          {selectedData.additionalNotes && (
                            <div className="space-y-2">
                              <h4 className="font-medium">Additional Notes</h4>
                              <p className="text-sm text-muted-foreground">{selectedData.additionalNotes}</p>
                            </div>
                          )}
                        </div>
                      </ScrollArea>
                    </TabsContent>

                    <TabsContent value="outline">
                      <ScrollArea className="h-[calc(100vh-400px)]">
                        <div className="flex items-center justify-between mb-4 pr-4">
                          <div className="flex items-center gap-2">
                            <Badge variant="outline" className="bg-green-500/10 text-green-600">
                              DeepSeek {selectedData.aiOutline ? "Ready" : "Pending"}
                            </Badge>
                            <Badge variant="outline" className="bg-blue-500/10 text-blue-600">
                              MiniMax {(selectedData as any).geminiOutline ? "Ready" : "Pending"}
                            </Badge>
                          </div>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => regenerateMutation.mutate(selectedData.id)}
                            disabled={regenerateMutation.isPending}
                            data-testid="button-regenerate"
                          >
                            {regenerateMutation.isPending ? (
                              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                            ) : (
                              <RefreshCw className="w-4 h-4 mr-2" />
                            )}
                            Regenerate Both
                          </Button>
                        </div>

                        {(selectedData.aiOutline || (selectedData as any).geminiOutline) ? (
                          <div className="pr-4 space-y-4">
                            {/* AI Analysis Section - only show when both outlines exist */}
                            {selectedData.aiOutline && (selectedData as any).geminiOutline && analysis && (
                              <div className="space-y-4 p-4 bg-muted/50 rounded-lg border">
                                <div className="flex items-center justify-between">
                                  <h3 className="font-semibold flex items-center gap-2">
                                    <Bot className="w-5 h-5" /> AI Comparison Analysis
                                  </h3>
                                  <Button
                                    variant="default"
                                    size="sm"
                                    onClick={() => mergeMutation.mutate(selectedData.id)}
                                    disabled={mergeMutation.isPending}
                                    data-testid="button-merge"
                                  >
                                    {mergeMutation.isPending ? (
                                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    ) : (
                                      <Merge className="w-4 h-4 mr-2" />
                                    )}
                                    Merge Best of Both
                                  </Button>
                                </div>
                                
                                <ConfidenceIndicator score={analysis.confidenceScore} />
                                
                                <div className="grid md:grid-cols-2 gap-4">
                                  <AgreementsList agreements={analysis.agreements} />
                                  {analysis.discrepancies.length > 0 && (
                                    <DiscrepancyAlerts discrepancies={analysis.discrepancies} />
                                  )}
                                </div>
                              </div>
                            )}

                            {/* Merged Outline Display */}
                            {(selectedData as any).mergedOutline && (
                              <Alert className="border-purple-500/50 bg-purple-500/10">
                                <Merge className="h-4 w-4 text-purple-600" />
                                <AlertTitle className="text-purple-600">Merged Outline Available</AlertTitle>
                                <AlertDescription className="text-sm">
                                  A best-of-both merged outline has been generated. Check the "Merged" tab below.
                                </AlertDescription>
                              </Alert>
                            )}

                            <Tabs defaultValue="openai">
                              <TabsList className={`grid w-full mb-4 ${(selectedData as any).mergedOutline ? 'grid-cols-3' : 'grid-cols-2'}`}>
                                <TabsTrigger value="openai" className="flex items-center gap-2" data-testid="tab-openai">
                                  <span className="w-2 h-2 rounded-full bg-green-500" />
                                  OpenAI (GPT-4o)
                                  <Badge variant="secondary" className="ml-1 text-xs">Client View</Badge>
                                </TabsTrigger>
                                <TabsTrigger value="gemini" className="flex items-center gap-2" data-testid="tab-gemini">
                                  <span className="w-2 h-2 rounded-full bg-blue-500" />
                                  Gemini (2.5 Flash)
                                </TabsTrigger>
                                {(selectedData as any).mergedOutline && (
                                  <TabsTrigger value="merged" className="flex items-center gap-2" data-testid="tab-merged">
                                    <span className="w-2 h-2 rounded-full bg-purple-500" />
                                    Merged
                                    <Badge className="ml-1 text-xs bg-purple-500/20 text-purple-600">Best of Both</Badge>
                                  </TabsTrigger>
                                )}
                              </TabsList>

                              <TabsContent value="openai">
                                {selectedData.aiOutline ? (
                                  <OutlineDisplay outline={selectedData.aiOutline as any} providerName="OpenAI GPT-4o" />
                                ) : (
                                  <NoOutlineMessage provider="OpenAI" />
                                )}
                              </TabsContent>

                              <TabsContent value="gemini">
                                {(selectedData as any).geminiOutline ? (
                                  <OutlineDisplay outline={(selectedData as any).geminiOutline} providerName="Google Gemini 2.5 Flash" />
                                ) : (
                                  <NoOutlineMessage provider="Gemini" />
                                )}
                              </TabsContent>

                              {(selectedData as any).mergedOutline && (
                                <TabsContent value="merged">
                                  <OutlineDisplay outline={(selectedData as any).mergedOutline} providerName="Merged (Best of Both)" />
                                </TabsContent>
                              )}
                            </Tabs>
                          </div>
                        ) : (
                          <div className="text-center py-12">
                            <Bot className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
                            <h3 className="font-semibold mb-2">No Outlines Generated Yet</h3>
                            <p className="text-muted-foreground mb-4">
                              The AI outlines are still being processed or haven't been generated.
                            </p>
                            <Button
                              onClick={() => regenerateMutation.mutate(selectedData.id)}
                              disabled={regenerateMutation.isPending}
                              data-testid="button-generate-outline"
                            >
                              {regenerateMutation.isPending ? (
                                <>
                                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                  Generating...
                                </>
                              ) : (
                                <>
                                  <Sparkles className="w-4 h-4 mr-2" />
                                  Generate Outlines
                                </>
                              )}
                            </Button>
                          </div>
                        )}
                      </ScrollArea>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
            ) : (
              <Card className="h-[calc(100vh-200px)] flex items-center justify-center">
                <div className="text-center">
                  <Eye className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
                  <h3 className="font-semibold mb-2">Select a Request</h3>
                  <p className="text-muted-foreground">
                    Click on a request from the list to view its details
                  </p>
                </div>
              </Card>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
